project:
  type: website
  render:
    - "*.qmd"
    - "!py-polars.qmd"

website:
  title: "DuckDB + Polars"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - requirements.qmd
      - sidebar:slides
      - sidebar:duckdb
      - sidebar:polars
    tools:
      - icon: github
        href:  https://github.com/grantmcdermott/duckdb-polars
        
  sidebar:
    - id: slides
      title: "Slides"
      style: "docked"
      background: light
      contents:
        - slides/slides.qmd
    - id: duckdb
      title: "DuckDB"
      style: "docked"
      background: light
      contents:
        - duckdb-sql.qmd
        - duckdb-dplyr.qmd
        - duckdb-ibis.qmd
    - id: polars
      title: "Polars"
      style: "docked"
      background: light
      contents:
        - polars-rpy.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



